-- Criação do schema
DROP SCHEMA IF EXISTS EST_CASO_V;
CREATE SCHEMA EST_CASO_V;
USE EST_CASO_V;

-- Criação das tabelas


CREATE TABLE IF NOT EXISTS CLIENTES (
  CLIENTE_ID INT PRIMARY KEY AUTO_INCREMENT,
  CLIENTE_NOME VARCHAR(200) NOT NULL,
  CLIENTE_CPF CHAR(11) UNIQUE NOT NULL,
  CLIENTE_DATA_NASC DATE NOT NULL,
  CLIENTE_ENDERECO VARCHAR(255) NOT NULL,
  CLIENTE_CIDADE VARCHAR(50) NOT NULL,
  CLIENTE_ESTADO CHAR(2) NOT NULL,
  CLIENTE_FIDELIDADE_STATUS BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS FORNECEDORES (
  FORNECEDOR_ID INT PRIMARY KEY AUTO_INCREMENT,
  FORNECEDOR_NOME VARCHAR(100) NOT NULL,
  FORNECEDOR_CONTATO VARCHAR(100),
  FORNECEDOR_TELEFONE CHAR(11),
  FORNECEDOR_EMAIL VARCHAR(100)
);



CREATE TABLE IF NOT EXISTS PRODUTOS (
  PRODUTO_ID INT PRIMARY KEY AUTO_INCREMENT,
  PRODUTO_NOME VARCHAR(100) NOT NULL,
  PRODUTO_CATEGORIA VARCHAR(50),
  PRODUTO_PRECO DECIMAL(10, 2) NOT NULL,
  PRODUTO_ESTOQUE INT NOT NULL,
  FORNECEDOR_ID INT NOT NULL,
  CONSTRAINT FK_PROD_FORNECEDOR FOREIGN KEY (FORNECEDOR_ID) REFERENCES FORNECEDORES(FORNECEDOR_ID)
);




CREATE TABLE IF NOT EXISTS VENDAS (
  VENDA_ID INT PRIMARY KEY AUTO_INCREMENT,
  CLIENTE_ID INT NOT NULL,
  VENDA_DATA DATE NOT NULL,
  VENDA_TOTAL DECIMAL(10, 2) NOT NULL,
  CONSTRAINT FK_VENDA_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(CLIENTE_ID)
);


CREATE TABLE IF NOT EXISTS VENDAS_PRODUTOS (
  VENDA_ID INT NOT NULL,
  PRODUTO_ID INT NOT NULL,
  QUANTIDADE INT NOT NULL,
  PRIMARY KEY (VENDA_ID, PRODUTO_ID),
  CONSTRAINT FK_VP_VENDA FOREIGN KEY (VENDA_ID) REFERENCES VENDAS(VENDA_ID),
  CONSTRAINT FK_VP_PRODUTO FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTOS(PRODUTO_ID)
);


CREATE TABLE IF NOT EXISTS PAGAMENTOS (
  PAGAMENTO_ID INT PRIMARY KEY AUTO_INCREMENT,
  VENDA_ID INT NOT NULL,
  PAGAMENTO_DATA DATE NOT NULL,
  PAGAMENTO_VALOR DECIMAL(10, 2) NOT NULL,
  PAGAMENTO_STATUS ENUM('pago', 'pendente') NOT NULL,
  CONSTRAINT FK_PAGAMENTO_VENDA FOREIGN KEY (VENDA_ID) REFERENCES VENDAS(VENDA_ID)
);

-- Alter Table das tabelas


ALTER TABLE CLIENTES 
  ADD COLUMN CLIENTE_EMAIL VARCHAR(100); 

ALTER TABLE CLIENTES 
  DROP COLUMN CLIENTE_EMAIL; 

ALTER TABLE CLIENTES 
  MODIFY COLUMN CLIENTE_NOME VARCHAR(255); 

ALTER TABLE CLIENTES 
  CHANGE COLUMN CLIENTE_ENDERECO CLIENTE_RUA VARCHAR(255);


ALTER TABLE PRODUTOS 
  ADD COLUMN PRODUTO_DESC VARCHAR(255);

ALTER TABLE PRODUTOS 
  DROP COLUMN PRODUTO_DESC;

ALTER TABLE PRODUTOS 
  MODIFY COLUMN PRODUTO_PRECO DECIMAL(12, 2);

ALTER TABLE PRODUTOS 
  CHANGE COLUMN PRODUTO_ESTOQUE PRODUTO_QUANTIDADE INT;


ALTER TABLE FORNECEDORES 
  ADD COLUMN FORNECEDOR_ENDERECO VARCHAR(255);

ALTER TABLE FORNECEDORES 
  DROP COLUMN FORNECEDOR_ENDERECO;

ALTER TABLE FORNECEDORES 
  MODIFY COLUMN FORNECEDOR_TELEFONE VARCHAR(15);

ALTER TABLE FORNECEDORES 
  CHANGE COLUMN FORNECEDOR_CONTATO FORNECEDOR_RESPONSAVEL VARCHAR(100);


ALTER TABLE VENDAS 
  ADD COLUMN VENDA_NOTA_FISCAL VARCHAR(20);

ALTER TABLE VENDAS 
  DROP COLUMN VENDA_NOTA_FISCAL;

ALTER TABLE VENDAS 
  MODIFY COLUMN VENDA_TOTAL DECIMAL(12, 2);

ALTER TABLE VENDAS 
  CHANGE COLUMN VENDA_DATA DATA_VENDA DATE;


ALTER TABLE VENDAS_PRODUTOS 
  ADD COLUMN PRECO_UNITARIO DECIMAL(10, 2);

ALTER TABLE VENDAS_PRODUTOS 
  DROP COLUMN PRECO_UNITARIO;

ALTER TABLE VENDAS_PRODUTOS 
  MODIFY COLUMN QUANTIDADE SMALLINT;

ALTER TABLE VENDAS_PRODUTOS 
  CHANGE COLUMN QUANTIDADE QTDE_COMPRADA INT;


ALTER TABLE PAGAMENTOS 
  ADD COLUMN FORMA_PAGAMENTO ENUM('dinheiro', 'cartao', 'pix');

ALTER TABLE PAGAMENTOS 
  DROP COLUMN FORMA_PAGAMENTO;

ALTER TABLE PAGAMENTOS 
  MODIFY COLUMN PAGAMENTO_VALOR DECIMAL(12, 2);

ALTER TABLE PAGAMENTOS 
  CHANGE COLUMN PAGAMENTO_DATA DATA_PAGAMENTO DATE;
